site_name: Documentation
site_url: https://documentation.secondstage.io
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
theme:
  name: material
  logo: assets/2s-logo.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.path
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
      primary: root
      accent: red

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode
      primary: root
      accent: red

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference
      primary: root
      accent: red

      
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/secondstage/
  homepage: https://documentation.secondstage.io
  generator: false
  
# Extensions 
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      title: Table of contents
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search

copyright: |
  &copy; 2024 <a href="https://secondstage.io"  target="_blank" rel="noopener">Second Stage GmbH</a>

# Page tree 
nav:
  - Home: index.md
  - TRACKS: 
    - Platform Overview: tracks/overview.md
    - Marketing Analytics: tracks/marketing-analytics.md
    - Attribution Tracking: tracks/attribution-tracking.md
    - Data Handling & Security: tracks/data-security.md
  - GATEWAY: 
    - Platform Overview: gateway/overview.md
  - Reference:
    - Glossary: glossary.md 
    - Further Reading: resources.md
  - Changelog:
    - changelog.md


