site_name: Documentation
site_url: https://documentation.secondstage.io
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: assets/2s-logo.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.path
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
  # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: root
      accent: red 
  # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: root
      accent: red
      
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/secondstage/
  homepage: https://documentation.secondstage.io    
  
# Extensions 
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      title: Table of contents
      permalink: true

plugins:
  - search

copyright: |
  &copy; 2024 <a href="https://secondstage.io"  target="_blank" rel="noopener">Second Stage GmbH</a>

# Page tree 
nav:
  - Home: index.md
  - TRACKS: 
    - Overview: tracks/overview.md
    - Marketing Analytics: tracks/marketing-analytics.md
    - Attribution Tracking: tracks/attribution-tracking.md
    - Data Handling & Security: tracks/data-security.md
  - GATEWAY: 
    - Overview: gateway/overview.md
  - Reference:
    - Glossary: glossary.md 
    - Further Reading: resources.md
  - Changelog:
    - changelog.md


